<?php
/**
 +-----------------------------------------------+
 | This file is part of chem-inventory.          |
 |                                               |
 | Copyright 2020                                |
 | Sandor Semsey <semseysandor@gmail.com>        |
 | All rights reserved.                          |
 |                                               |
 | This work is published under the MIT License. |
 | https://choosealicense.com/licenses/mit/      |
 +-----------------------------------------------+
 */

namespace Inventory\Page;

use Inventory\Core\Controller\Page;

/**
 * Forms Controller
 *
 * @category Controller
 * @package  chem-inventory_oop
 * @author   Sandor Semsey <semseysandor@gmail.com>
 * @license  MIT https://choosealicense.com/licenses/mit/
 * php version 7.4
 */
class Forms extends Page
{
    private string $type;

    private string $entity;

    /**
     * Validate input
     */
    protected function validate(): void
    {
        parent::validate(); // TODO: Change the autogenerated stub
        $majom = 5;
        $this->type = $this->routeParams['type'] ?? '';
        $this->entity = $this->routeParams['entity'] ?? '';

        if (empty($this->type) || empty($this->entity)) {
            $this->errorFlag = true;
            http_response_code(204);
        }
    }

    /**
     * Process input
     */
    protected function process(): void
    {
        parent::process(); // TODO: Change the autogenerated stub
    }

    /**
     * Assemble page
     */
    protected function assemble(): void
    {
        parent::assemble(); // TODO: Change the autogenerated stub
    }

}
